server:
  port: 8090
  servlet:
    context-path: /resource-server

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/emr
          jwk-set-uri: http://localhost:8083/auth/realms/emr/protocol/openid-connect/certs