server:
  port: 8083
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password
    keyStoreType: PKCS12
    keyALias: keycloak

security:
  require-ssl: true

  spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: emr-admin
      password: pass
    realmImportFile: emr-realm.json


#john@test.com / 123
#mike@other.com / pass
#[root@ip-10-0-57-186 greatbig.club]# openssl pkcs12 -export -in fullchain.pem -inkey privkey.pem -out keystore.p12 -name keycloak -CAfile chain.pem -caname root
#Enter Export Password: password
#Verifying - Enter Export Password: password